### PR TITLE
add msbuild props and update csproj files so they work better with bazel outputs

### PR DESCRIPTION
**Pull request by JonnyOThan**

### CODE REVIEW

**Comment by djungelorm** [comment]
Thanks. I want to check this works in my build env first, then will get this merged

**Review by djungelorm — CHANGES_REQUESTED** [review]
Looks good to me.

My only query is why we need to change the platform version from v4.5 to v4.5.2?

**Comment by djungelorm** [comment]
Changelog notes for when I do the next release:
 - Updated csproj files to build portable debug info
 - Updated framework version from 4.5 to 4.5.2
 - Improved support for building csproj files on Windows and MacOS (will look in correct path for KSP libraries)

**Comment by JonnyOThan** [comment]
> My only query is why we need to change the platform version from v4.5 to v4.5.2?

I was unable to find the .net framework build tools for 4.5.  I expect they’ve been discontinued for security vulnerabilities. If someone didn’t already have it installed, they wouldn’t be able to build.

**Review by djungelorm — APPROVED** [review]

**Comment by SofieBrink** [comment]
See [this](https://stackoverflow.com/questions/70022194/open-net-framework-4-5-project-in-vs-2022-is-there-any-workaround) article for further reference.

**Pull request merged**
