### PR TITLE
Added size and colour parameters to UI.Message()

### PR DESCRIPTION
**Pull request by Somfic**
This adds parameters to change the default size and colour of messages when using UI.Message().
Added the size and color parameter, modified the summary as well.

### CODE REVIEW

**Comment by Somfic** [comment]
Namespaces cannot be added.

**Comment by djungelorm** [comment]
I don't follow why you abandoned this. What went wrong?

**Comment by Somfic** [comment]
Travis Ci kept giving namespace errors

**Comment by djungelorm** [comment]
I managed to get it to work - see the commit above.

I used a slightly esoteric kRPC feature to allow color to be treated as a default parameter (using KRPCDefaultValue to work around the C# limitation that you can't have an object as the default value)

I also reordered the parameters to put the new color and size parameters at the end, to maintain backwards compatibility for older code.

**Comment by Somfic** [comment]
That's great!

**Pull request closed without merging**
