### PR TITLE
Protocol Changes in v0.4.x

### PR DESCRIPTION
**Pull request by djungelorm**
Changes to the communication protocol are coming in v0.4.0. These will break backwards compatibility and will require client libraries to be updated. Client _scripts_ are unaffected. The following describes the changes, and the rationale behind them.

The new protobuf definitions are available here: https://github.com/krpc/krpc/blob/v0.4.0/protobuf/krpc.proto 

Feedback on the changes is welcome! As this affects third-party clients I'm happy to help update them before it's released. (Paging @TeWu and @Cahu)

Pre-release builds of v0.4.0 are available from the Travis CI server here:
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/v0.4.0/

# 1. Removing unnecessary message fields

The following unnecessary fields have been removed (as discussed in #264):
- `Response.has_error` - to check for an error, you can just check if `Response.error` is non-empty.
- `Response.has_return_value` - whether a response will have a return value or not is determined by the return type of the procedure, so this information does not need to be sent with every response.
- `Parameter.has_default_value` - to check whether a parameter has a default value, you can check whether `Parameter.default_value` is empty.
- `Procedure.has_return_type` - this information is now contained in the return type of the procedure.

# 2. Batched RPCs

Previously, only a single remote call could be sent in a request message. Request messages now support multiple calls, and the corresponding response messages returns the results of the calls.

The order of the RPC calls in a request message (`Request.calls`) is the same as the order of the results in the corresponding response message (`Response.results`).

# 3. Changes to `GetServices()`

The `Services` message returned by `KRPC.GetServices()` was very space inefficient and made it hard for clients to interpret due to its use of type strings and attributes. The following changes have been made to improve this.

## 3a. Types

Procedure parameter and return types (the `Parameter.type` and `Procedure.return_type` protobuf message fields) used to be encoded as strings, for example `int32`, `Class(SpaceCenter.Vessel)` or `List(string)`. These have been changed to use a protobuf message called `Type`, which are defined here: https://github.com/krpc/krpc/blob/v0.4.0/protobuf/krpc.proto#L108
- The `Type.code` field specifies the type. `NONE` is used as the return type for procedures that do not return a value.
- For `CLASS` and `ENUMERATION` types the `Type.service` and   `Type.name` fields will contain the service that defines the class/enum and   the name of the class/enum. For all other types these fields are empty.
- For collection types the `Type.types` repeated field will contain the   sub-types:
  - `TUPLE` types contain 1 or more types in the `Type.types` field.
  - `LIST` and `SET` types contain a single type in the `Type.types`
    field.
  - `DICTIONARY` types contain a 2 types in the `Type.types`     field - the key and value types, in that order.
  - For all other types the `Types.types` field is empty.

This representation allows class, enumeration and collection types to be specified directly in the `Type` field for a procedure parameter or return type. They used to be expressed using a combination of a type and an 'attribute'. For example, if a procedure returned a list of integers, it would have return   type `List` and attribute `ReturnType.List(int32)` (both as strings). This is now represented by a single `Type` message, so the attribute is no longer required:

```
  Type {
    code = LIST,
    types = [ Type { code = SINT32 } ]
  }
```

And a class type used to be represented by, `ReturnType.Class(ServiceName.ClassName)`. It is now represented by a `Type` message as follows:

```
  Type {
    code = CLASS,
    service = 'ServiceName',
    name = 'ClassName'
  }
```

Using protobuf messages for types has several benefits:
- The result of `GetServices()` is _much_ smaller (on the order to 25% smaller for the RPCs currently on the server).
- Types are much easier, and faster, for client libraries to parse. Complex string parsing is no longer required.

## 3b. Procedure names

Attributes used to be used to specify whether a procedure is a service procedure, class method, class property, etc. and what class (if any) it belongs to. However, this can be determined from the name of the procedure:
- 'ProcedureName' - a standard procedure that is just part of a service.
- 'get_PropertyName' - a procedure that returns the value of a property in a service.
- 'set_PropertyName' - a procedure that sets the value of a property in a service.
- 'ClassName_MethodName' - a class method.
- 'ClassName_static_StaticMethodName' - a static class method.
- 'ClassName_get_PropertyName' - a class property getter.
- 'ClassName_set_PropertyName' - a class property setter.

Note: only letters and numbers are permitted in class/method/property names, so the underscores here can be used to split the name into its constituent parts.

## 3c. Attributes

With the changes to types and procedure names, the old attributes are unnecessary and so have been removed.
# 4. Service definition files

The service definition JSON files generated by `krpc-servicedefs` have also been modified in line with the changes above.

# 5. Encoding of signed integers

int32 and int64 types have been changed to use sint32 and sint64. This makes use of protocol buffers' zig zag encoding, which provides a much more compact encoding for negative numbers.

# 6. Connecting to the server

The way clients connect to the server is changing. Currently, to connect, a client sends some magic bytes followed by a client name to the server, then receives a client identifier (that is used to connect to the stream server). The new protocol is as follows:
- Send a `ConnectionRequest` protobuf message, with the type field set to `RPC`, and containing the (optional) clients name.
- Receive a `ConnectionResponse` protobuf message, containing the clients identifier. This also contains a status field and status message that are populated by the server to indicate if the connection was successful, and if not, why not.

The stream server connection protocol works similarly:
- Send a `ConnectionRequest` protobuf message, with the type field set to `STREAM` and client identifier set to the value returned in the connection response when connecting to the RPC server.
- Receive a `ConnectionResponse` protobuf message, and check the status field.

This connection protocol is essentially the same as before, but uses protobuf messages to encode the information sent between client and server. This means that the connection request/response messages are extensible (new fields can be added without breaking backwards compatibility) and the client code is made a bit simpler (you can just use the protobuf library to, for example. encode the client name).

# 7. Nullable

Procedures, properties and methods are now marked explicitly if they may return a null value. This information is included in the service definition files and in the information sent by calling ``GetServices``

# 8. Events

Support for events has been added to the server. Documentation is available here:
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/v0.4.0/1038.1/doc/communication-protocols/messages.html#events
http://krpc.s3-website-us-east-1.amazonaws.com/deploy/v0.4.0/1038.1/doc/extending.html#events

### CODE REVIEW

**Comment by Cahu** [comment]
Hi djungelorm,

I am not able to connect when using the latest build. Can you please explain the new handshake a bit more ?

I've been unsuccessful doing the following :
* as before, send the magic bytes "HELLO-RPC\x0\x0\x0" (is this part necessary ? can you remove that step for v0.4 ?),
* send a ConnectionRequest message with the client_name field set to some character string and the client_identifier unset.

I get the response MALFORMED_HEADER with no explanation in the 'message' field.

**Comment by Cahu** [comment]
After reading your code, I noticed that the magic bytes have changed. Using the new string "KRPC-RPC" gets me further. It appears I am able to receive a ConnectionResponse with a client_identifier. However, the status field does not seem to be set. I was expecting the 'OK' value from the enum in the schema.

**Comment by djungelorm** [comment]
The status field should always be set - it's not an optional field. In fact, there are no optional fields in protobuf3! OK has value of 0, so the field being "unset" is probably equivalent to it being set to OK. This might be a quirk of the haskell protobuf library?

And yes I changed the magic bytes to avoid old clients from getting through the first step of the connection protocol. That's what the malformed header message means. I've been thinking, maybe we should just remove these magic bytes entirely? I don't think they really gain us anything useful - just make it harder to implement a client.

**Comment by Cahu** [comment]
I agree, I don't think the first step with the magic string is necessary. The initial message could be the connection request. If you are using those magic bytes to prevent old clients from connecting, you could do the same for future versions by adding some king of 'supported version' number in the ConnectionRequest and/or ConnectionResponse.

From what I understand, on the contrary, all fields in protobuf v3 are optional. But there seems to be an exception for 'primitive' types (enums could be one of them) being always present in v3; which make sense from a 'compactness' standpoint. If that is correct, then I only need to change the proto file I adapted for my v2-compliant library.

**Comment by Cahu** [comment]
Well, I was able to work around the problem of this 'unset' field by adding a default value to the status field in the proto file. The problem is that tagging fields as 'required' won't work and, when using 'optional' instead, the null value coincides with the 'OK' value.

It is increasingly difficult to make the proto file compatible with a decoder that only supports protobuf v2. Unfortunately, I don't think there are, at the moment, mature and well maintained implementation for protobuf v3 in Haskell.

Since kRPC doesn't require v3 features, would you consider using v2 instead ? That would be temporary since there's a semi-official proto-lens library (which should support v3) from google being developed.

**Comment by djungelorm** [comment]
I've done some testing using the python protobuf v3 library. The binary representation for a connection response message with the status field set to OK is just `00` (in hex, i.e. a single zero byte). For a message with the status set to MALFORMED_HEADER the binary is `020801`. So looks like they optimise out the "OK" value as it's the default value anyway.

Calling `message.HasField('status')` to see if the field is set always returns this error:
`ValueError: Protocol message has no non-repeated submessage field "status"`

It looks like the field is just optional in the sense that you don't have to set it, and if you don't it will take the default value ("OK" in this case). I think it is safe to equate not set as meaning the same as "OK".

I don't want to downgrade to v2, as that would involve quite a changes to all the clients. kRPC used to use v2, and upgrading it to v3 took some effort! I think it's less effort to have a workaround in the haskell client until the haskell v3 support gets better?

**Comment by djungelorm** [comment]
I've removed the magic bytes. However, I did realise one use for them is to check if you are connecting to the correct server. It's an easy mistake if you get the port numbers swapped. I've therefore added a `type` field to the `ConnectionRequest` message that should be set to either `RPC` or `STREAM`.

Here's the latest build: https://krpc.s3.amazonaws.com/deploy/v0.4.0/711.1/krpc-0.3.6-71-g0b567c1.zip

**Comment by Cahu** [comment]
Why not make a separate connection request messages? It's best to encode the purpose of a message in it's type rather than with a flag in a do-it-all message. You could have an RPCConnectionRequest  (with the client name) and a StreamConnectionRequest (with a client ID).

When you write "Calling message.HasField('status') to see if the field is set always returns this error", does this mean that your client also sees the field as not being set? If so, you might want to set a default value in the proto file; like so:
```
message ConnectionResponse {
  Status status = 1 [ default = OK ];
  enum Status {
    OK = 0;
...
  }
...
}
```

**Comment by djungelorm** [comment]
As far as I can tell, the python library doesn't have a notion of enum fields being optional. They always have a value. The value is only optional in the binary representation, and if omitted there, is assumed to be set to 0.

That default is implicit, so making that change would have no effect. `OK` has a value of 0, and is therefore the default. https://developers.google.com/protocol-buffers/docs/proto3#enum

**Comment by TeWu** [comment]
@djungelorm  I would appreciate if you could fix headers formatting in [the first comment][1]. Also `4a. Types` should be `3a. Types` and `3c. Attributes` should be formatted as second level header.
I could fix those and few other minor formatting issues if I had necessary permissions.

[1]: https://github.com/krpc/krpc/pull/325#issue-167524077

**Comment by djungelorm** [comment]
I've fixed the formatting. Thanks for pointing it out - not sure how I missed that...

**Comment by TeWu** [comment]
Could you please share compiled version of [TestServer][1] from `v0.4.0` branch?

[1]: https://github.com/krpc/krpc/tree/v0.4.0/tools/TestServer

**Comment by djungelorm** [comment]
Here you go! [TestServer.zip](https://github.com/krpc/krpc/files/595636/TestServer.zip)

**Comment by TeWu** [comment]
Thanks, but I can't run it:

``` shell
tewu@sparcle:~/Downloads/bazel-bin/tools/TestServer$ ./TestServer.exe

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'KRPC, Version=0.3.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'KRPC, Version=0.3.6.0, Culture=neutral, PublicKeyToken=null'
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'KRPC, Version=0.3.6.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'KRPC, Version=0.3.6.0, Culture=neutral, PublicKeyToken=null'
```

**Comment by Cahu** [comment]
Hi,
I think there is a problem with the way stream IDs are encoded. I use the same deserializer for the stream ID in the response of AddStream and in a StreamResult (uint64).

I can decode the stream ID in a StreamResult just fine but the ID in the response of AddStream has a byte (with the value 0x08) before the actual stream ID.

Can you make sure that you are using the same serialization method for both cases ?

**Comment by Cahu** [comment]
Hi,
I think there is a problem with the way stream IDs are encoded. I use the same deserializer for the stream ID in the response of AddStream and in a StreamResult (uint64).

I can decode the stream ID in a StreamResult just fine but the ID in the response of AddStream has a byte (with the value 0x08) in front preventing me from decoding the id properly.

Can you make sure that you are using the same serialization method for both cases ?

**Comment by TeWu** [comment]
@Cahu response to `AddStream` is a `Stream` message, not an `uint64`.

**Comment by Cahu** [comment]
@TeWu Indeed it is, thanks!

**Comment by TeWu** [comment]
So having [finished][2] upgrading kRPC-rb I can give you some feedback:

**1. I can't connect if `Auto-accept new clients` is unchecked:**

```shell
[1] pry(main)> require 'krpc'
=> true
[2] pry(main)> cl = KRPC.connect
KRPC::ConnectionError: TIMEOUT -- The operation has timed-out.
from /home/tewu/.rvm/gems/ruby-2.3.0@krpc/gems/krpc-0.4.0.beta1/lib/krpc/connection.rb:55:in `protobuf_handshake'
```

I tried this also with Python client, and the result is the same:

```shell
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import krpc
>>> cl = krpc.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/krpc/__init__.py", line 33, in connect
krpc.error.ConnectionError: The operation has timed-out.
```

This was done using python client version [`0.3.6-71-g0b567c1`][1] and the same version of kRPC server.

**2. I'm getting error from `SpaceCenter.warp_to` method:**

``` shell
>>> import krpc
>>> conn = krpc.connect()
>>> sc = conn.space_center
>>> sc.warp_to(sc.ut + 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "build/bdist.linux-x86_64/egg/krpc/client.py", line 88, in _invoke
krpc.error.RPCError: Method not found: 'TimeWarp.SetRate'.
>>> sc.ut + 100
21932.243213115966
```

I can also reproduce this using ruby client - so I would say it's a server side issue.

**3. Missing TestSever** - not really that 0.4.0-specific, so I made a separate issue for this one: #363.

[1]: http://krpc.s3-website-us-east-1.amazonaws.com/deploy/v0.4.0/711.1/
[2]: https://github.com/TeWu/krpc-rb/pull/9

**Pull request merged**
