### PR TITLE
Updated Primary API to 1.10

### PR DESCRIPTION
**Pull request by kylewill0725**
Done:
- Updated KRPC, KRPC.Drawing, KRPC.UI, and KRPC.SpaceCenter to .Net 4.0
- Cleaned up references a bit for people who don't use build system.
- Misc fixes for Unity 2019.2.2f
- Updated ksp version max to 1.10.1.2939

### CODE REVIEW

**Review by crwgrant — APPROVED** [review]

**Comment by kylewill0725** [comment]
Converted to draft as I need to go through the release steps.

**Comment by djungelorm** [comment]
Thanks for all your hard work! Although I lack the time to work on the code these days, I would be happy to post a new release once you think it's ready.

**Comment by kylewill0725** [comment]
Happy to hear it. It has been a really fun project to update. Hopefully it will be ready in the next few days. The main things I'm working on for release are:
- [ ] Move all bazel-* dependencies in csproj files to a `generated` folder in the root of the repository. This will be generated by Bazel ideally.
- [ ] Create a Python stub generator using clientgen.
- [ ] Add the new robotics parts to kRPC
- [ ] Double check Release Guide

**Comment by djungelorm** [comment]
In case you didn't already find it, the script in tools/dist/genfiles.sh should build all the files needed to use the csproj files without bazel. Might help with the first task you mention.

**Comment by kylewill0725** [comment]
Some background for the first task; I'm currently working on a Windows machine but in order to build the full project (docs, client libs, etc) I need to use Bazel on Linux so I use WSL. However, I like to use Visual Studio when working on the C# code of the mod. The problem I have is that the csproj files point to files inside `bazel-bin`. This is fine if I'm just compiling the dll's because I can use the zip file you mentioned and it's all good. The issue comes from frequently running `bazel build` in this setup. Every time it's run, the `bazel-*` folders get deleted by Bazel. It then replaces them with a Linux symlink which Visual Studio cannot access.

My solution is to add a new subtarget to `//:csproj` which takes all of the csproj dependencies and copies them to a `generated_deps` folder at the root of the repository. I understand this is poor Bazel design as you are not supposed to modify the source folder itself but, in my opinion, it makes developing the full project on Windows easier.

You can see the rule I used to accomplish this [here](https://github.com/kylewill0725/krpc/commit/033704f6b344fe12595cad2a8055d27aa3a16f0a#diff-3053677e4333a96b20ed76c662bca07fb2e1ce059479170139209356787da09cR332)

**Comment by kylewill0725** [comment]
I've successfully added python to the clientgen. Sadly I've run out of time to put towards this update right now so I'll be completing the final release build step tomorrow, merging the changes into my release branch, and marking the pull request as "Ready for Review". Implementing the robotics parts will have to wait for another time. For anyone reading this, I believe you can still use [Module](https://krpc.github.io/krpc/python/api/space-center/parts.html#SpaceCenter.Module) to control robotics, though I haven't tested it myself.

**Comment by kylewill0725** [comment]
Finished checking the Release Guide and the only issue is there are 3 tests that fail. `//client/python:lint` sees a bunch of the types needed for type checking as unused and there are a few false positives of cyclic imports when a class is imported for types (aka it's not imported at runtime).
`//client/python:test2` errors:
```
======================================================================
FAIL: test_rate (krpc.test.test_stream.TestStream)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/.cache/bazel/_bazel_asdf/a21f739b07394fc1e10f8c32d0627847/sandbox/linux-sandbox/7687/execroot/krpc/bazel-out/k8-fastbuild/bin/client/python/test2.runfiles/krpc/test-executable.runfiles/krpc/client/python/py2test.runfiles/krpc/krpc-0.4.9/krpc/test/test_stream.py", line 430, in test_rate
    self.assertGreater(elapsed, 1)
AssertionError: 0.11406993865966797 not greater than 1

----------------------------------------------------------------------
```
`//client/python:test3` errors:
```
======================================================================
FAIL: test_event (krpc.test.test_event.TestEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/.cache/bazel/_bazel_asdf/a21f739b07394fc1e10f8c32d0627847/sandbox/linux-sandbox/8438/execroot/krpc/bazel-out/k8-fastbuild/bin/client/python/test3.runfiles/krpc/test-executable.runfiles/krpc/client/python/py3test.runfiles/krpc/krpc-0.4.9/build/lib/krpc/test/test_event.py", line 18, in test_event
    self.assertAlmostEqual(time.time()-start_time, 0.2, delta=0.05)
AssertionError: 0.2628791332244873 != 0.2 within 0.05 delta

======================================================================
FAIL: test_event_loop (krpc.test.test_event.TestEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/asdf/.cache/bazel/_bazel_asdf/a21f739b07394fc1e10f8c32d0627847/sandbox/linux-sandbox/8438/execroot/krpc/bazel-out/k8-fastbuild/bin/client/python/test3.runfiles/krpc/test-executable.runfiles/krpc/client/python/py3test.runfiles/krpc/krpc-0.4.9/build/lib/krpc/test/test_event.py", line 58, in test_event_loop
    time.time()-start_time, 0.2*repeat, delta=0.05)
AssertionError: 0.8507223129272461 != 0.8 within 0.05 delta

----------------------------------------------------------------------
```

I'm not really sure how to debug these last two. Are these breaking errors?

**Comment by kylewill0725** [comment]
I reran the `//client/python:test3` outside of bazel and there were no errors. I suspect that these timing issues come from an interaction of being inside the WSL virtual machine. When I tried the same with `//client/python:test2` I still had several tests fail.

**Comment by Genhis** [comment]
If I may ask, what are the benefits of your python clientgen compared to the current approach?

**Comment by kylewill0725** [comment]
There is nothing comparable in the current approach. Python [PEP 484](https://www.python.org/dev/peps/pep-0484/#stub-files) allows typing annotations to be added to your codebase which editors can use to give better autocompletion. For example, PyCharm can now suggest `active_vessel` when `conn.space_center` is typed. This could not happen before as all services are generated at runtime and editors had no information about that.

**Comment by kylewill0725** [comment]
Is there an update on the status of this pull request?

**Comment by djungelorm** [comment]
Sorry just not had time - don't worry I've not forgotten!

**Comment by djungelorm** [comment]
I've had a look at the changes - looks great! And I can compile it fine :)

Only thing I noticed is that its no longer compatible with KSP pre 1.10 due to the unity upgrade they did with 1.10. So I will update the mod to only be listed as compatible with 1.10

**Pull request merged**
